version: "3"

services:
  logpaste:
    image: solo4444/logpaste
    container_name: logpaste
    restart: always
    ports:
      - 8091:3001
    environment:
      - "PORT=3001"
      - "LITESTREAM_ACCESS_KEY_ID=${LITESTREAM_ACCESS_KEY_ID}"
      - "LITESTREAM_SECRET_ACCESS_KEY=${LITESTREAM_SECRET_ACCESS_KEY}"
      - "LITESTREAM_REGION=${LITESTREAM_REGION}"
      - "DB_REPLICA_URL=${DB_REPLICA_URL}"
